In [57]:
!pip install selenium
!pip install undetected-chromedriver
     
import undetected_chromedriver.v2 as uc
import time
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: selenium in c:\users\srividya\anaconda3\lib\site-packages (4.0.0b4)
Requirement already satisfied: trio~=0.17 in c:\users\srividya\anaconda3\lib\site-packages (from selenium) (0.19.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\srividya\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[secure]~=1.26 in c:\users\srividya\anaconda3\lib\site-packages (from selenium) (1.26.4)
Requirement already satisfied: async-generator>=1.9 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: attrs>=19.2.0 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (20.3.0)
Requirement already satisfied: idna in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.10)
Requirement already satisfied: outcome in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: sniffio in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.14.5)
Requirement already satisfied: pycparser in c:\users\srividya\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\srividya\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.0.0)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (3.4.7)
Requirement already satisfied: certifi in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (2020.12.5)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (20.0.1)
Requirement already satisfied: six>=1.5.2 in c:\users\srividya\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure]~=1.26->selenium) (1.15.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\srividya\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.12.0)
Requirement already satisfied: undetected-chromedriver in c:\users\srividya\anaconda3\lib\site-packages (3.0.3)
Requirement already satisfied: websockets in c:\users\srividya\anaconda3\lib\site-packages (from undetected-chromedriver) (10.0)
Requirement already satisfied: selenium==4.0.0b4 in c:\users\srividya\anaconda3\lib\site-packages (from undetected-chromedriver) (4.0.0b4)
Requirement already satisfied: requests in c:\users\srividya\anaconda3\lib\site-packages (from undetected-chromedriver) (2.25.1)
Requirement already satisfied: urllib3[secure]~=1.26 in c:\users\srividya\anaconda3\lib\site-packages (from selenium==4.0.0b4->undetected-chromedriver) (1.26.4)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\srividya\anaconda3\lib\site-packages (from selenium==4.0.0b4->undetected-chromedriver) (0.9.2)
Requirement already satisfied: trio~=0.17 in c:\users\srividya\anaconda3\lib\site-packages (from selenium==4.0.0b4->undetected-chromedriver) (0.19.0)
Requirement already satisfied: cffi>=1.14 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (1.14.5)
Requirement already satisfied: idna in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (2.10)
Requirement already satisfied: sortedcontainers in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (2.3.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (20.3.0)
Requirement already satisfied: outcome in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (1.1.0)
Requirement already satisfied: sniffio in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (1.2.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (1.10)
Requirement already satisfied: pycparser in c:\users\srividya\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\srividya\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium==4.0.0b4->undetected-chromedriver) (1.0.0)
Requirement already satisfied: certifi in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium==4.0.0b4->undetected-chromedriver) (2020.12.5)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium==4.0.0b4->undetected-chromedriver) (20.0.1)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium==4.0.0b4->undetected-chromedriver) (3.4.7)
Requirement already satisfied: six>=1.5.2 in c:\users\srividya\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure]~=1.26->selenium==4.0.0b4->undetected-chromedriver) (1.15.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\srividya\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.0.0b4->undetected-chromedriver) (0.12.0)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\srividya\anaconda3\lib\site-packages (from requests->undetected-chromedriver) (4.0.0)

In [58]:
import selenium
import pandas as pd
from selenium import webdriver 
from selenium.common.exceptions import  StaleElementReferenceException
from selenium.common.exceptions import  NoSuchElementException,NoSuchWindowException

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

In [59]:
driver = uc.Chrome()
with driver:
    driver.get(r"C:\Users\Srividya\Downloads\undetected-chromedriver-3.0.3.tar.gz")

In [60]:
url="https://www.myntra.com/shoes"
driver.get(url)

In [61]:
try:
    price=driver.find_elements_by_xpath("//label[@class='common-customCheckbox vertical-filters-label']")
    for k in price:
        if k.text=="Rs. 6897 to Rs. 13595(1877)":
            k.click()
    
except StaleElementReferenceException as e:
       time.sleep(1)

In [62]:
try: 
    color=driver.find_elements_by_xpath("//span[@class='colour-label colour-colorDisplay']")
    for l in color:
        if l.text=="Black (16609)":
             l.click()  
            
except StaleElementReferenceException as e:
       time.sleep(1)

In [25]:
Brands=[]
Brand=driver.find_elements_by_xpath("//h3[@class='product-brand']")
for a in Brand:
    Brands.append(a.text)
Brands

['Red Tape',
 'Newfeel By Decathlon',
 'Puma',
 'PUMA Motorsport',
 'Provogue',
 'Woakers',
 'Nike',
 'Catwalk',
 'Reebok',
 'Red Tape',
 'Eego Italy',
 'Alishtezia',
 'H&M',
 'Provogue',
 'Nike',
 'Red Tape',
 'H&M',
 'Red Tape',
 'Roadster',
 'Red Tape',
 'AfroJack',
 'Puma',
 'HRX by Hrithik Roshan',
 'Mast & Harbour',
 'FAST TRAX',
 'ZAPATOZ',
 'Nike',
 'Red Tape',
 'HRX by Hrithik Roshan',
 'Red Tape',
 'U.S. Polo Assn.',
 'Roadster',
 'Provogue',
 'Catwalk',
 'Mast & Harbour',
 'LOCOMOTIVE',
 'Nike',
 'Roadster',
 'HRX by Hrithik Roshan',
 'ID',
 'Walkstyle By El Paso',
 'Mast & Harbour',
 'HRX by Hrithik Roshan',
 'Red Tape',
 'DressBerry',
 'H&M',
 'Red Tape',
 'FILA',
 'MENGLER',
 'U.S. Polo Assn.']

In [26]:
shoe_descs=[]
try:
    shoe_desc=driver.find_elements_by_xpath("//h4[@class='product-product']")
    for b in shoe_desc:
        shoe_descs.append(b.text)
except  NoSuchElementException as e:
        shoe_descs.append("_")
shoe_descs

['Men Sneakers',
 'Men Walking Shoes',
 'Men Running Enzo 2 Shoes',
 'Unisex Sf Drift Cat 5 Ultra Sneakers',
 'Men Walking Sports Shoes',
 'Men Running Shoes',
 'Men Flex Run 2021 Running Shoe',
 'Women Flatform Brogues',
 'Men Solecure Running',
 'Men Walking Shoes',
 'Men Trekking Shoes',
 'Women Colourblocked PU Sneakers',
 'Men Espadrilles',
 'Men Solid Loafers',
 'Men FlexRun 2021 Running Shoes',
 'Men Colourblocked Sneakers',
 'Men Trainers',
 'Men Sneakers',
 'Men Sneakers',
 'Men Walking Shoes',
 'Men Running Shoes',
 'Women Zone XT Running Shoes',
 'Men Front Runner Shoes',
 'Men Slip-On Sneakers',
 'Men White Slip-On Sneakers',
 'Wedge Mules',
 'Men Renew Retaliation TR 3',
 'Men Woven Design Sneakers',
 'Men FlexStreet Athleisure Shoe',
 'Men Air + Walking Shoes',
 'Men LEBRON 2.0 Walking Shoes',
 'Men Slip-On Sneakers',
 'Men Solid Horsebit Loafers',
 'Women Sandals',
 'Men Woven Design Sneakers',
 'Men Sneakers',
 'Men FLEX EXPERIENCE RN Shoes',
 'Men Slip-On Sneakers',
 'Men Gamescape Sneakers',
 'Men Derbys',
 'Men Running Shoes',
 'Men Perforations Loafers',
 'Women Running Shoes',
 'Women Walking Shoes',
 'Women Solid Flats',
 'Women Hi-top twill trainers',
 'Men DRIFT+ Walking Shoes',
 'Men Colourblocked Sneakers',
 'Men Walking Shoes',
 'Men Walking Shoes']

In [27]:
prices=[]
price=driver.find_elements_by_xpath("//div[@class='product-price']")
for c in price:
    prices.append(c.text)
prices

['Rs. 1049Rs. 4699(Rs. 3650 OFF)',
 'Rs. 899',
 'Rs. 2474Rs. 5499(55% OFF)',
 'Rs. 3149Rs. 6999(55% OFF)',
 'Rs. 699Rs. 3395(Rs. 2696 OFF)',
 'Rs. 681Rs. 3405(80% OFF)',
 'Rs. 6795',
 'Rs. 2306Rs. 3295(30% OFF)',
 'Rs. 2799Rs. 3999(30% OFF)',
 'Rs. 1224Rs. 4899(75% OFF)',
 'Rs. 987Rs. 2599(62% OFF)',
 'Rs. 799Rs. 1599(50% OFF)',
 'Rs. 649Rs. 1299(50% OFF)',
 'Rs. 799Rs. 3995(80% OFF)',
 'Rs. 6795',
 'Rs. 1049Rs. 4399(Rs. 3350 OFF)',
 'Rs. 2299',
 'Rs. 1049Rs. 4699(Rs. 3650 OFF)',
 'Rs. 1499Rs. 2999(50% OFF)',
 'Rs. 1224Rs. 4899(75% OFF)',
 'Rs. 699Rs. 2663(Rs. 1964 OFF)',
 'Rs. 4199Rs. 6999(40% OFF)',
 'Rs. 1329Rs. 3799(65% OFF)',
 'Rs. 1159Rs. 2899(60% OFF)',
 'Rs. 699Rs. 1499(Rs. 800 OFF)',
 'Rs. 679Rs. 999(32% OFF)',
 'Rs. 5995',
 'Rs. 1049Rs. 4399(Rs. 3350 OFF)',
 'Rs. 2204Rs. 4899(55% OFF)',
 'Rs. 1824Rs. 7299(75% OFF)',
 'Rs. 2199Rs. 3999(45% OFF)',
 'Rs. 999Rs. 1999(50% OFF)',
 'Rs. 799Rs. 3699(Rs. 2900 OFF)',
 'Rs. 1319Rs. 2095(37% OFF)',
 'Rs. 1574Rs. 3499(55% OFF)',
 'Rs. 696Rs. 995(30% OFF)',
 'Rs. 4995',
 'Rs. 999Rs. 1999(50% OFF)',
 'Rs. 2159Rs. 4799(55% OFF)',
 'Rs. 1794Rs. 3985(Rs. 2191 OFF)',
 'Rs. 681Rs. 2199(69% OFF)',
 'Rs. 1299Rs. 2599(50% OFF)',
 'Rs. 1399Rs. 3999(65% OFF)',
 'Rs. 924Rs. 3699(75% OFF)',
 'Rs. 849Rs. 1699(50% OFF)',
 'Rs. 1199Rs. 1999(40% OFF)',
 'Rs. 1499Rs. 5999(75% OFF)',
 'Rs. 2399Rs. 3999(40% OFF)',
 'Rs. 624Rs. 2499(75% OFF)',
 'Rs. 1999Rs. 3999(50% OFF)']

In [28]:
Nos=[]
for i in range(1,len(Brands)+1):
    Nos.append(i)
Nos

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [29]:
Brandss=[]
shoe_descss=[]
pricess=[]

In [30]:
for j in range(2,4):
    next_btn=driver.find_element_by_xpath("//a[@rel='next']")
    next_btn.click()
    time.sleep(1)    
    #driver.get(current_url)
    time.sleep(1)
    Brande=''
    Product_descse=''
    pricesse=''
    Brande=driver.find_elements_by_xpath("//h3[@class='product-brand']")
    for o in Brande:
        Brandss.append(o.text)
    time.sleep(1) 
    try:
        Product_descse=driver.find_elements_by_xpath("//h4[@class='product-product']") 
        for p in Product_descse:
             shoe_descss.append(p.text)
    except  NoSuchElementException as e:
             shoe_descss.append("_")
    time.sleep(1)    
    pricesse=driver.find_elements_by_xpath("//div[@class='product-price']")
    for q in pricesse:
        pricess.append(q.text)
    time.sleep(1)

In [31]:
Brandss

['Red Tape',
 'Campus',
 'FILA',
 'Sparx',
 'Nike',
 'LONDON STEPS',
 'H&M',
 'SCENTRA',
 'one8 x PUMA',
 'U.S. Polo Assn.',
 'HRX by Hrithik Roshan',
 'Puma',
 'Nike',
 'Puma',
 'SUBEA By Decathlon',
 'U.S. Polo Assn.',
 'TWIN TOES',
 'FAST TRAX',
 'H&M',
 'HRX by Hrithik Roshan',
 'Provogue',
 'Red Tape',
 'Sparx',
 'ZAPATOZ',
 'Yuuki',
 'Mast & Harbour',
 'Anouk',
 'H&M',
 'Nike',
 'House of Pataudi',
 'Bella Toes',
 'Red Tape',
 'HRX by Hrithik Roshan',
 'H&M',
 'WROGN',
 'Mode by Red Tape',
 'H&M',
 'Puma',
 'Nike',
 'Red Tape',
 'Red Tape',
 'ELIXIR MAN',
 'MANGO',
 'Puma',
 'DressBerry',
 'Mactree',
 'Sparx',
 'Kook N Keech',
 'Roadster',
 'Duke',
 'Nike',
 'Puma',
 'Woodland',
 'H&M',
 'FAUSTO',
 'Artengo By Decathlon',
 'Sparx',
 'Roadster',
 'HRX by Hrithik Roshan',
 'Nike',
 'H&M',
 'FAST TRAX',
 'H&M',
 'HRX by Hrithik Roshan',
 'Provogue',
 'Red Tape',
 'FILA',
 'Skechers',
 'Mactree',
 'Nike',
 'H&M',
 'HRX by Hrithik Roshan',
 'MENGLER',
 'Mast & Harbour',
 'ZAPATOZ',
 'MONKS & KNIGHTS',
 'ZAPATOZ',
 'mr.wonker',
 'HIROLAS',
 'Fentacia',
 'Nike',
 'H&M',
 'DressBerry',
 'House of Pataudi',
 'HRX by Hrithik Roshan',
 'Provogue',
 'Provogue',
 'H&M',
 'FILA',
 'Allen Cooper',
 'Red Tape',
 'Roadster',
 'Sparx',
 'Sir Corbett',
 'Provogue',
 'HRX by Hrithik Roshan',
 'U.S. Polo Assn.',
 'Puma',
 'Nike',
 'H&M']

In [32]:
shoe_descss

['Men Striped Sneakers',
 'Men Running Shoes',
 'Men Textured Sneakers',
 'Men Running Shoes',
 'Men Flex 2021 Running Shoes',
 'Women Platform Heeled Boots',
 'Women Mules',
 'Women Block Braided Heels',
 'Men Smash Mid-Cut Sneakers',
 'Men Amiston Walking Shoes',
 'Men Atom Running Shoe',
 'Men Running Shoes',
 'Men Flex Run 2021 Running Shoe',
 'Men Sneakers',
 'Unsiex Aqua Shoes 100',
 'Men Leather Loafers',
 'Women NA Colourblocked Sneakers',
 'Men Slip-On Sneakers',
 'Mens Hi-top trainers',
 'Men FlexStreet Athleisure Shoe',
 'Men Woven Design Sneakers',
 'Men Walking Shoes',
 'Men Running Shoes',
 'Gold Textured Wedge Sandals',
 'Men Running Shoes',
 'Men Sneakers',
 'Women Colourblocked Mules',
 'Mens Trainers',
 'Men Renew Retaliation TR 3',
 'Men Handcrafted Loafers',
 'Women Sneakers',
 'Men DRIFT+ Walking Shoes',
 'Men Knit Run 1.2 Running Shoes',
 'Platform trainers',
 'Men Solid Sneakers',
 'Women Open Toe Flats',
 'Men Canvas Hi-Top Trainers',
 'Men Flexracer 20 IDP Running Shoes',
 'JORDAN ONE TAKE II Basketball',
 'Men Leather Driving Shoes',
 'Men Air + Walking Shoes',
 'Men Sneakers',
 'Women Solid Sneakers',
 'Sneakers',
 'Women Braided Open Toe Flats',
 'Men Woven Design Nubuck Slip-On Sneakers',
 'Men Running Shoes',
 'Men Slip-On Sneakers',
 'Men Sneakers',
 'Men Running Shoes',
 'Men City Rep Training Shoes',
 'Men Sneakers',
 'Men Sneakers',
 'Women Solid Canvas Trainers',
 'Men Lace Up Sneakers',
 'Men Tennis Shoes',
 'Running Shoes',
 'Men Sneakers',
 'Men Chunky Sneakers',
 'Men CITY REP TR Training Shoes',
 'Men Black Low Profile Trainers',
 'Men Woven Design Sneakers',
 'Women Solid Sandals',
 'Men Road Running Shoes',
 'Men Knitted Upper Running Sport Shoes',
 'Men Walking Shoes',
 'Unisex Slip-On Sneakers',
 'Women RUMBLE ON Sandals',
 'Men Solid Sneakers',
 'Men Zoom Span 3 Running Shoes',
 'Men Solid Canvas Trainers',
 'Men Front Runner Shoe',
 'Men Running Shoes',
 'Men Sneakers',
 'Women White Walking Shoes',
 'Men Textured Leather Loafers',
 'Women Heeled Boots',
 'Men Running Shoes',
 'Men Running Shoes',
 'Men Loafers',
 'Unisex FLYBY MID 2 Basketball',
 'Men Solid Mesh Trainers',
 'Women Solid Wedges',
 'Men Textured Slip Ons',
 'Men Soft Walk Slip-on Shoe',
 'Men Walking Sports Shoes',
 'Men Synthetic Leather Loafers',
 'Looney Tunes Printed Trainers',
 'Men Running Shoes',
 'Men Running Shoes',
 'Men Sneakers',
 'Men Solid Sneakers',
 'Men SM-677 Running Shoes',
 'Men Oxford Formal Shoes',
 'Men Solid Penny Loafers',
 'Men Alpha Running Shoe',
 'Men Solid Sneakers',
 'Unisex Perforated Low IDP Run',
 'Men JORDAN WHY NOT ZER0 Shoes',
 'Men White Low profile trainers']

In [33]:
pricess

['Rs. 1299Rs. 5199(75% OFF)',
 'Rs. 1315Rs. 1399(6% OFF)',
 'Rs. 2099Rs. 3499(40% OFF)',
 'Rs. 986Rs. 1049(6% OFF)',
 'Rs. 6795',
 'Rs. 799Rs. 999(20% OFF)',
 'Rs. 1379Rs. 2299(40% OFF)',
 'Rs. 999Rs. 1999(50% OFF)',
 'Rs. 2999Rs. 4999(40% OFF)',
 'Rs. 3599Rs. 4799(25% OFF)',
 'Rs. 2024Rs. 4499(55% OFF)',
 'Rs. 3024Rs. 5499(45% OFF)',
 'Rs. 6795',
 'Rs. 2949Rs. 4999(41% OFF)',
 'Rs. 664Rs. 699(5% OFF)',
 'Rs. 2529Rs. 4599(45% OFF)',
 'Rs. 799Rs. 999(Rs. 200 OFF)',
 'Rs. 699Rs. 1499(Rs. 800 OFF)',
 'Rs. 2299',
 'Rs. 2204Rs. 4899(55% OFF)',
 'Rs. 699Rs. 3495(80% OFF)',
 'Rs. 1224Rs. 4899(75% OFF)',
 'Rs. 986Rs. 1049(6% OFF)',
 'Rs. 729Rs. 999(27% OFF)',
 'Rs. 896Rs. 2299(61% OFF)',
 'Rs. 1349Rs. 2999(55% OFF)',
 'Rs. 854Rs. 1899(55% OFF)',
 'Rs. 2299',
 'Rs. 5995',
 'Rs. 3224Rs. 4299(25% OFF)',
 'Rs. 699Rs. 999(30% OFF)',
 'Rs. 1499Rs. 5999(75% OFF)',
 'Rs. 1574Rs. 3499(55% OFF)',
 'Rs. 1199Rs. 1999(40% OFF)',
 'Rs. 1374Rs. 2499(45% OFF)',
 'Rs. 674Rs. 2699(75% OFF)',
 'Rs. 1999',
 'Rs. 1799Rs. 2999(40% OFF)',
 'Rs. 8295',
 'Rs. 1574Rs. 6299(75% OFF)',
 'Rs. 1749Rs. 6999(75% OFF)',
 'Rs. 539Rs. 1999(73% OFF)',
 'Rs. 1436Rs. 3590(60% OFF)',
 'Rs. 1749Rs. 3499(50% OFF)',
 'Rs. 764Rs. 1699(55% OFF)',
 'Rs. 849Rs. 2830(70% OFF)',
 'Rs. 996Rs. 1049(5% OFF)',
 'Rs. 1349Rs. 2999(55% OFF)',
 'Rs. 1499Rs. 2999(50% OFF)',
 'Rs. 1562Rs. 4595(66% OFF)',
 'Rs. 4995',
 'Rs. 3249Rs. 4999(35% OFF)',
 'Rs. 2656Rs. 3795(30% OFF)',
 'Rs. 899Rs. 1499(40% OFF)',
 'Rs. 719Rs. 899(20% OFF)',
 'Rs. 1304Rs. 1499(13% OFF)',
 'Rs. 1329Rs. 1399(5% OFF)',
 'Rs. 1449Rs. 2899(50% OFF)',
 'Rs. 1919Rs. 4799(60% OFF)',
 'Rs. 4995',
 'Rs. 1499',
 'Rs. 699Rs. 1499(Rs. 800 OFF)',
 'Rs. 1379Rs. 2299(40% OFF)',
 'Rs. 1259Rs. 3599(65% OFF)',
 'Rs. 679Rs. 3395(80% OFF)',
 'Rs. 1224Rs. 4899(75% OFF)',
 'Rs. 1999',
 'Rs. 2199Rs. 3999(45% OFF)',
 'Rs. 649Rs. 2164(70% OFF)',
 'Rs. 7195',
 'Rs. 1499',
 'Rs. 2204Rs. 4899(55% OFF)',
 'Rs. 624Rs. 2499(75% OFF)',
 'Rs. 1304Rs. 2899(55% OFF)',
 'Rs. 799Rs. 1599(50% OFF)',
 'Rs. 1539Rs. 6999(78% OFF)',
 'Rs. 699Rs. 999(30% OFF)',
 'Rs. 624Rs. 2499(75% OFF)',
 'Rs. 839Rs. 2799(70% OFF)',
 'Rs. 829Rs. 2514(67% OFF)',
 'Rs. 4995',
 'Rs. 2999',
 'Rs. 804Rs. 2299(65% OFF)',
 'Rs. 2089Rs. 3799(45% OFF)',
 'Rs. 1349Rs. 2999(55% OFF)',
 'Rs. 699Rs. 2995(Rs. 2296 OFF)',
 'Rs. 648Rs. 2595(75% OFF)',
 'Rs. 1999',
 'Rs. 1049Rs. 2099(50% OFF)',
 'Rs. 944Rs. 4295(78% OFF)',
 'Rs. 1049Rs. 4699(Rs. 3650 OFF)',
 'Rs. 999Rs. 1999(50% OFF)',
 'Rs. 996Rs. 1049(5% OFF)',
 'Rs. 824Rs. 2749(70% OFF)',
 'Rs. 674Rs. 2595(74% OFF)',
 'Rs. 2159Rs. 4799(55% OFF)',
 'Rs. 2399Rs. 3999(40% OFF)',
 'Rs. 2799Rs. 3999(30% OFF)',
 'Rs. 11495',
 'Rs. 1499']

In [34]:
Brands.extend(Brandss)
shoe_descs.extend(shoe_descss)
prices.extend(pricess)

In [35]:
Brands

['Red Tape',
 'Newfeel By Decathlon',
 'Puma',
 'PUMA Motorsport',
 'Provogue',
 'Woakers',
 'Nike',
 'Catwalk',
 'Reebok',
 'Red Tape',
 'Eego Italy',
 'Alishtezia',
 'H&M',
 'Provogue',
 'Nike',
 'Red Tape',
 'H&M',
 'Red Tape',
 'Roadster',
 'Red Tape',
 'AfroJack',
 'Puma',
 'HRX by Hrithik Roshan',
 'Mast & Harbour',
 'FAST TRAX',
 'ZAPATOZ',
 'Nike',
 'Red Tape',
 'HRX by Hrithik Roshan',
 'Red Tape',
 'U.S. Polo Assn.',
 'Roadster',
 'Provogue',
 'Catwalk',
 'Mast & Harbour',
 'LOCOMOTIVE',
 'Nike',
 'Roadster',
 'HRX by Hrithik Roshan',
 'ID',
 'Walkstyle By El Paso',
 'Mast & Harbour',
 'HRX by Hrithik Roshan',
 'Red Tape',
 'DressBerry',
 'H&M',
 'Red Tape',
 'FILA',
 'MENGLER',
 'U.S. Polo Assn.',
 'Red Tape',
 'Campus',
 'FILA',
 'Sparx',
 'Nike',
 'LONDON STEPS',
 'H&M',
 'SCENTRA',
 'one8 x PUMA',
 'U.S. Polo Assn.',
 'HRX by Hrithik Roshan',
 'Puma',
 'Nike',
 'Puma',
 'SUBEA By Decathlon',
 'U.S. Polo Assn.',
 'TWIN TOES',
 'FAST TRAX',
 'H&M',
 'HRX by Hrithik Roshan',
 'Provogue',
 'Red Tape',
 'Sparx',
 'ZAPATOZ',
 'Yuuki',
 'Mast & Harbour',
 'Anouk',
 'H&M',
 'Nike',
 'House of Pataudi',
 'Bella Toes',
 'Red Tape',
 'HRX by Hrithik Roshan',
 'H&M',
 'WROGN',
 'Mode by Red Tape',
 'H&M',
 'Puma',
 'Nike',
 'Red Tape',
 'Red Tape',
 'ELIXIR MAN',
 'MANGO',
 'Puma',
 'DressBerry',
 'Mactree',
 'Sparx',
 'Kook N Keech',
 'Roadster',
 'Duke',
 'Nike',
 'Puma',
 'Woodland',
 'H&M',
 'FAUSTO',
 'Artengo By Decathlon',
 'Sparx',
 'Roadster',
 'HRX by Hrithik Roshan',
 'Nike',
 'H&M',
 'FAST TRAX',
 'H&M',
 'HRX by Hrithik Roshan',
 'Provogue',
 'Red Tape',
 'FILA',
 'Skechers',
 'Mactree',
 'Nike',
 'H&M',
 'HRX by Hrithik Roshan',
 'MENGLER',
 'Mast & Harbour',
 'ZAPATOZ',
 'MONKS & KNIGHTS',
 'ZAPATOZ',
 'mr.wonker',
 'HIROLAS',
 'Fentacia',
 'Nike',
 'H&M',
 'DressBerry',
 'House of Pataudi',
 'HRX by Hrithik Roshan',
 'Provogue',
 'Provogue',
 'H&M',
 'FILA',
 'Allen Cooper',
 'Red Tape',
 'Roadster',
 'Sparx',
 'Sir Corbett',
 'Provogue',
 'HRX by Hrithik Roshan',
 'U.S. Polo Assn.',
 'Puma',
 'Nike',
 'H&M']

In [36]:
shoe_descs

['Men Sneakers',
 'Men Walking Shoes',
 'Men Running Enzo 2 Shoes',
 'Unisex Sf Drift Cat 5 Ultra Sneakers',
 'Men Walking Sports Shoes',
 'Men Running Shoes',
 'Men Flex Run 2021 Running Shoe',
 'Women Flatform Brogues',
 'Men Solecure Running',
 'Men Walking Shoes',
 'Men Trekking Shoes',
 'Women Colourblocked PU Sneakers',
 'Men Espadrilles',
 'Men Solid Loafers',
 'Men FlexRun 2021 Running Shoes',
 'Men Colourblocked Sneakers',
 'Men Trainers',
 'Men Sneakers',
 'Men Sneakers',
 'Men Walking Shoes',
 'Men Running Shoes',
 'Women Zone XT Running Shoes',
 'Men Front Runner Shoes',
 'Men Slip-On Sneakers',
 'Men White Slip-On Sneakers',
 'Wedge Mules',
 'Men Renew Retaliation TR 3',
 'Men Woven Design Sneakers',
 'Men FlexStreet Athleisure Shoe',
 'Men Air + Walking Shoes',
 'Men LEBRON 2.0 Walking Shoes',
 'Men Slip-On Sneakers',
 'Men Solid Horsebit Loafers',
 'Women Sandals',
 'Men Woven Design Sneakers',
 'Men Sneakers',
 'Men FLEX EXPERIENCE RN Shoes',
 'Men Slip-On Sneakers',
 'Men Gamescape Sneakers',
 'Men Derbys',
 'Men Running Shoes',
 'Men Perforations Loafers',
 'Women Running Shoes',
 'Women Walking Shoes',
 'Women Solid Flats',
 'Women Hi-top twill trainers',
 'Men DRIFT+ Walking Shoes',
 'Men Colourblocked Sneakers',
 'Men Walking Shoes',
 'Men Walking Shoes',
 'Men Striped Sneakers',
 'Men Running Shoes',
 'Men Textured Sneakers',
 'Men Running Shoes',
 'Men Flex 2021 Running Shoes',
 'Women Platform Heeled Boots',
 'Women Mules',
 'Women Block Braided Heels',
 'Men Smash Mid-Cut Sneakers',
 'Men Amiston Walking Shoes',
 'Men Atom Running Shoe',
 'Men Running Shoes',
 'Men Flex Run 2021 Running Shoe',
 'Men Sneakers',
 'Unsiex Aqua Shoes 100',
 'Men Leather Loafers',
 'Women NA Colourblocked Sneakers',
 'Men Slip-On Sneakers',
 'Mens Hi-top trainers',
 'Men FlexStreet Athleisure Shoe',
 'Men Woven Design Sneakers',
 'Men Walking Shoes',
 'Men Running Shoes',
 'Gold Textured Wedge Sandals',
 'Men Running Shoes',
 'Men Sneakers',
 'Women Colourblocked Mules',
 'Mens Trainers',
 'Men Renew Retaliation TR 3',
 'Men Handcrafted Loafers',
 'Women Sneakers',
 'Men DRIFT+ Walking Shoes',
 'Men Knit Run 1.2 Running Shoes',
 'Platform trainers',
 'Men Solid Sneakers',
 'Women Open Toe Flats',
 'Men Canvas Hi-Top Trainers',
 'Men Flexracer 20 IDP Running Shoes',
 'JORDAN ONE TAKE II Basketball',
 'Men Leather Driving Shoes',
 'Men Air + Walking Shoes',
 'Men Sneakers',
 'Women Solid Sneakers',
 'Sneakers',
 'Women Braided Open Toe Flats',
 'Men Woven Design Nubuck Slip-On Sneakers',
 'Men Running Shoes',
 'Men Slip-On Sneakers',
 'Men Sneakers',
 'Men Running Shoes',
 'Men City Rep Training Shoes',
 'Men Sneakers',
 'Men Sneakers',
 'Women Solid Canvas Trainers',
 'Men Lace Up Sneakers',
 'Men Tennis Shoes',
 'Running Shoes',
 'Men Sneakers',
 'Men Chunky Sneakers',
 'Men CITY REP TR Training Shoes',
 'Men Black Low Profile Trainers',
 'Men Woven Design Sneakers',
 'Women Solid Sandals',
 'Men Road Running Shoes',
 'Men Knitted Upper Running Sport Shoes',
 'Men Walking Shoes',
 'Unisex Slip-On Sneakers',
 'Women RUMBLE ON Sandals',
 'Men Solid Sneakers',
 'Men Zoom Span 3 Running Shoes',
 'Men Solid Canvas Trainers',
 'Men Front Runner Shoe',
 'Men Running Shoes',
 'Men Sneakers',
 'Women White Walking Shoes',
 'Men Textured Leather Loafers',
 'Women Heeled Boots',
 'Men Running Shoes',
 'Men Running Shoes',
 'Men Loafers',
 'Unisex FLYBY MID 2 Basketball',
 'Men Solid Mesh Trainers',
 'Women Solid Wedges',
 'Men Textured Slip Ons',
 'Men Soft Walk Slip-on Shoe',
 'Men Walking Sports Shoes',
 'Men Synthetic Leather Loafers',
 'Looney Tunes Printed Trainers',
 'Men Running Shoes',
 'Men Running Shoes',
 'Men Sneakers',
 'Men Solid Sneakers',
 'Men SM-677 Running Shoes',
 'Men Oxford Formal Shoes',
 'Men Solid Penny Loafers',
 'Men Alpha Running Shoe',
 'Men Solid Sneakers',
 'Unisex Perforated Low IDP Run',
 'Men JORDAN WHY NOT ZER0 Shoes',
 'Men White Low profile trainers']

In [40]:
prices

['Rs. 11999',
 'Rs. 6999',
 'Rs. 6999',
 'Rs. 6999',
 'Rs. 8099Rs. 8999(10% OFF)',
 'Rs. 8999Rs. 14999(40% OFF)',
 'Rs. 10999',
 'Rs. 10999',
 'Rs. 7999',
 'Rs. 10999',
 'Rs. 7195',
 'Rs. 12749Rs. 16999(25% OFF)',
 'Rs. 11999',
 'Rs. 6999Rs. 9999(30% OFF)',
 'Rs. 6999',
 'Rs. 7149Rs. 12999(45% OFF)',
 'Rs. 6999',
 'Rs. 7499',
 'Rs. 7649Rs. 8999(15% OFF)',
 'Rs. 9999',
 'Rs. 7999',
 'Rs. 8999Rs. 9999(10% OFF)',
 'Rs. 10999',
 'Rs. 8990',
 'Rs. 12999',
 'Rs. 7999',
 'Rs. 11199Rs. 13999(20% OFF)',
 'Rs. 9999',
 'Rs. 8999',
 'Rs. 8999',
 'Rs. 9999',
 'Rs. 7499',
 'Rs. 8999Rs. 9999(10% OFF)',
 'Rs. 6999',
 'Rs. 11999',
 'Rs. 9999',
 'Rs. 10999',
 'Rs. 8999',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 7999',
 'Rs. 12999',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 6999',
 'Rs. 12999',
 'Rs. 8999Rs. 9999(10% OFF)',
 'Rs. 11999',
 'Rs. 11999',
 'Rs. 10355Rs. 10900(5% OFF)',
 'Rs. 9999',
 'Rs. 7999',
 'Rs. 6999',
 'Rs. 9999',
 'Rs. 11999',
 'Rs. 6999',
 'Rs. 11305Rs. 11900(5% OFF)',
 'Rs. 10399Rs. 12999(20% OFF)',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 7499',
 'Rs. 12999',
 'Rs. 7499',
 'Rs. 6999',
 'Rs. 9999',
 'Rs. 7999Rs. 9999(20% OFF)',
 'Rs. 12999',
 'Rs. 9513Rs. 13590(30% OFF)',
 'Rs. 9999',
 'Rs. 9990',
 'Rs. 9990',
 'Rs. 11999',
 'Rs. 7799Rs. 11999(35% OFF)',
 'Rs. 6999',
 'Rs. 9093Rs. 12990(30% OFF)',
 'Rs. 7999',
 'Rs. 6999Rs. 9999(30% OFF)',
 'Rs. 6990',
 'Rs. 12495',
 'Rs. 9975Rs. 10500(5% OFF)',
 'Rs. 9999',
 'Rs. 11990',
 'Rs. 9999',
 'Rs. 8990',
 'Rs. 13490',
 'Rs. 11990',
 'Rs. 7999',
 'Rs. 10999',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 9799Rs. 13999(30% OFF)',
 'Rs. 9990',
 'Rs. 7400Rs. 14800(50% OFF)',
 'Rs. 12999',
 'Rs. 12999',
 'Rs. 7990',
 'Rs. 7990',
 'Rs. 11499',
 'Rs. 6999',
 'Rs. 6993Rs. 9990(30% OFF)',
 'Rs. 10999',
 'Rs. 9599Rs. 15999(40% OFF)',
 'Rs. 9999',
 'Rs. 9499',
 'Rs. 6999',
 'Rs. 6969Rs. 8499(18% OFF)',
 'Rs. 6999',
 'Rs. 8999',
 'Rs. 8295',
 'Rs. 11490',
 'Rs. 7999',
 'Rs. 10490',
 'Rs. 11495',
 'Rs. 9999',
 'Rs. 11999',
 'Rs. 9995',
 'Rs. 6999Rs. 9999(30% OFF)',
 'Rs. 12999',
 'Rs. 6993Rs. 9990(30% OFF)',
 'Rs. 6990',
 'Rs. 8253Rs. 11790(30% OFF)',
 'Rs. 8792Rs. 10990(20% OFF)',
 'Rs. 7599',
 'Rs. 8195',
 'Rs. 11999',
 'Rs. 7195',
 'Rs. 7990',
 'Rs. 12999',
 'Rs. 9999',
 'Rs. 12500',
 'Rs. 7990',
 'Rs. 6990',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 7799Rs. 12999(40% OFF)',
 'Rs. 8999',
 'Rs. 8999',
 'Rs. 9999',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 7799Rs. 12999(40% OFF)',
 'Rs. 9999',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 10999',
 'Rs. 9999',
 'Rs. 7199Rs. 11999(40% OFF)',
 'Rs. 9999']

In [41]:
Nos=[]
for i in range(1,len(Brands)+1):
    Nos.append(i)
Nos

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150]

In [42]:
import pandas as pd
myntra_SHoe=pd.DataFrame({})
myntra_SHoe['Nos']=Nos[:100]
myntra_SHoe['SNEAKER SHOE BRAND NAME']=Brands[:100]
myntra_SHoe['Product Description']=shoe_descs[:100]
myntra_SHoe['Price']=prices[:100]
myntra_SHoe.style.hide_index()

These are the First 100 Shoes from myntra