In [1]:
!pip install selenium
!pip install undetected-chromedriver
     
import undetected_chromedriver.v2 as uc
import time
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: selenium in c:\users\srividya\anaconda3\lib\site-packages (4.0.0b4)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\srividya\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: trio~=0.17 in c:\users\srividya\anaconda3\lib\site-packages (from selenium) (0.19.0)
Requirement already satisfied: urllib3[secure]~=1.26 in c:\users\srividya\anaconda3\lib\site-packages (from selenium) (1.26.4)
Requirement already satisfied: sortedcontainers in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.3.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (20.3.0)
Requirement already satisfied: outcome in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: idna in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.10)
Requirement already satisfied: sniffio in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.14.5)
Requirement already satisfied: async-generator>=1.9 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: pycparser in c:\users\srividya\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\srividya\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.0.0)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (3.4.7)
Requirement already satisfied: certifi in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (2020.12.5)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (20.0.1)
Requirement already satisfied: six>=1.5.2 in c:\users\srividya\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure]~=1.26->selenium) (1.15.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\srividya\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.12.0)
Requirement already satisfied: undetected-chromedriver in c:\users\srividya\anaconda3\lib\site-packages (3.0.3)
Requirement already satisfied: websockets in c:\users\srividya\anaconda3\lib\site-packages (from undetected-chromedriver) (10.0)
Requirement already satisfied: selenium==4.0.0b4 in c:\users\srividya\anaconda3\lib\site-packages (from undetected-chromedriver) (4.0.0b4)
Requirement already satisfied: requests in c:\users\srividya\anaconda3\lib\site-packages (from undetected-chromedriver) (2.25.1)
Requirement already satisfied: urllib3[secure]~=1.26 in c:\users\srividya\anaconda3\lib\site-packages (from selenium==4.0.0b4->undetected-chromedriver) (1.26.4)
Requirement already satisfied: trio~=0.17 in c:\users\srividya\anaconda3\lib\site-packages (from selenium==4.0.0b4->undetected-chromedriver) (0.19.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\srividya\anaconda3\lib\site-packages (from selenium==4.0.0b4->undetected-chromedriver) (0.9.2)
Requirement already satisfied: idna in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (2.10)
Requirement already satisfied: sniffio in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (1.14.5)
Requirement already satisfied: sortedcontainers in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (2.3.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (20.3.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (1.10)
Requirement already satisfied: outcome in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (1.1.0)
Requirement already satisfied: pycparser in c:\users\srividya\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium==4.0.0b4->undetected-chromedriver) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\srividya\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium==4.0.0b4->undetected-chromedriver) (1.0.0)
Requirement already satisfied: certifi in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium==4.0.0b4->undetected-chromedriver) (2020.12.5)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium==4.0.0b4->undetected-chromedriver) (3.4.7)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium==4.0.0b4->undetected-chromedriver) (20.0.1)
Requirement already satisfied: six>=1.5.2 in c:\users\srividya\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure]~=1.26->selenium==4.0.0b4->undetected-chromedriver) (1.15.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\srividya\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.0.0b4->undetected-chromedriver) (0.12.0)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\srividya\anaconda3\lib\site-packages (from requests->undetected-chromedriver) (4.0.0)

In [2]:
import selenium
import pandas as pd
from selenium import webdriver 
from selenium.common.exceptions import  StaleElementReferenceException
from selenium.common.exceptions import  NoSuchElementException,NoSuchWindowException

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

In [3]:
driver = uc.Chrome()
with driver:
    driver.get(r"C:\Users\Srividya\Downloads\undetected-chromedriver-3.0.3.tar.gz")

In [35]:
url="https://www.flipkart.com"
driver.get(url)

In [36]:
search_sneaker=driver.find_element_by_xpath("//input[@class='_3704LK']")
search_sneaker

In [37]:
search_sneaker.send_keys("sneakers")

In [38]:
search_btn=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_btn

In [39]:

search_btn.click()

In [40]:
Brands=[]
Brand=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
for a in Brand:
    Brands.append(a.text)
Brands

['woati',
 'Echor',
 'Chevit',
 'Magnolia',
 'BRUTON',
 'Chevit',
 'ASTEROID',
 'HRX by Hrithik Roshan',
 'Longwalk',
 'luxury fashion',
 'PEHANOSA',
 'Numenzo',
 'Creer',
 'ASTEROID',
 'Numenzo',
 'Bonexy',
 'BIRDE',
 'Numenzo',
 'SCATCHITE',
 'Echor',
 'Shoes Bank',
 'Absolute comfort',
 'Numenzo',
 'RED TAPE',
 'Arohi',
 'VIPSJAZZY',
 'RODDICK SHOES',
 'Bonexy',
 'Airland',
 'believe',
 'World Wear Footwear',
 'Zorth',
 'Robbie jones',
 'restinfoot',
 'bluemaker',
 'Chevit',
 'Numenzo',
 'Kraasa',
 'HOC',
 'ROCKFIELD']

In [41]:
len(Brands)

40

In [53]:
Product_desc=[]
try:
    Product_des=driver.find_elements_by_xpath("//a[@class='IRpwTa']")
    for b in Product_des:
        Product_desc.append(b.text)
except  NoSuchElementException as e:
        Product_desc.append("_")
Product_desc

["Men's Sneakers Walking Shoes - Lightweight Classic Whit...",
 'Super Stylish & Trendy Combo Pack of 02 Pairs Sneakers ...',
 'Sneakers For Men',
 'Combo Pack Of 4 Casual Shoes Loafer Shoes Sneakers For ...',
 'Perfect & Affordable Combo Pack of 02 Pairs Sneakers Ou...',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Sneakers For Men',
 'Men Boxer Sneakers For Men',
 'Luxury Fashionable casual sneaker shoes Sneakers For Me...',
 'Sneakers For Men',
 'Sneakers For Men',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Birde Trendy Casual Shoes Sneakers For Men',
 'Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Mens Walking Running Shoes - Lightweight Breathable Mes...',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Sneakers For Men',
 'Sneakers For Men',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'Sneakers For Men',
 'shoe Sneakers For Men',
 'Sneakers for men(black_6) Sneakers For Men',
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'Sneakers For Men',
 'Sneakers For Men',
 "Casual shoes,Sneakers for men's,shoes for men's Sneaker...",
 'casual for men (blue 10) Sneakers For Men',
 'Combo Pack of 4 Casual Sneakers With Sneakers For Men',
 'Sneakers For Men',
 'Series 7 Sneakers For Men',
 'Luxury Fashionable Breathable Casual Sneakers Shoes For...',
 'Sneakers For Men']

In [54]:
len(Product_desc)

33

In [57]:
prices=[]
price=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
for c in price:
    prices.append(c.text)
prices

['₹499',
 '₹399',
 '₹536',
 '₹356',
 '₹474',
 '₹447',
 '₹499',
 '₹1,699',
 '₹236',
 '₹379',
 '₹378',
 '₹449',
 '₹398',
 '₹499',
 '₹449',
 '₹474',
 '₹359',
 '₹449',
 '₹398',
 '₹399',
 '₹349',
 '₹198',
 '₹429',
 '₹899',
 '₹460',
 '₹399',
 '₹474',
 '₹379',
 '₹250',
 '₹449',
 '₹240',
 '₹434',
 '₹499',
 '₹349',
 '₹404',
 '₹424',
 '₹398',
 '₹444',
 '₹378',
 '₹499']

In [58]:
len(prices)

40

In [55]:
discount_percents=[]
discount_percent=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']")
for c in discount_percent:
    discount_percents.append(c.text)
discount_percents

['50% off',
 '60% off',
 '66% off',
 '64% off',
 '86% off',
 '75% off',
 '75% off',
 '56% off',
 '52% off',
 '70% off',
 '62% off',
 '77% off',
 '60% off',
 '50% off',
 '65% off',
 '52% off',
 '28% off',
 '77% off',
 '60% off',
 '60% off',
 '65% off',
 '60% off',
 '66% off',
 '78% off',
 '53% off',
 '60% off',
 '52% off',
 '62% off',
 '49% off',
 '55% off',
 '51% off',
 '56% off',
 '50% off',
 '65% off',
 '59% off',
 '78% off',
 '60% off',
 '55% off',
 '81% off',
 '50% off']

In [56]:
len(discount_percents)

40

In [61]:
Brandss=[]
Product_descs=[]
pricess=[]
discount_percentss=[]

In [62]:



for j in range(2,4):
    next_btn=driver.find_element_by_xpath("//a[@class='_1LKTO3']")
    next_btn.click()
    time.sleep(1)    
    #driver.get(current_url)
    time.sleep(1)
    Brande=''
    Product_descse=''
    pricesse=''
    discount_percentsse=''
    Brande=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
    for o in Brande:
        Brandss.append(o.text)
    time.sleep(1) 
    try:
        Product_descse=driver.find_elements_by_xpath("//a[@class='IRpwTa']") 
        for p in Product_descse:
             Product_descs.append(p.text)
    except  NoSuchElementException as e:
             Product_descs.append("_")
    time.sleep(1)    
    pricesse=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
    for q in pricesse:
        pricess.append(q.text)
    try:    
        discount_percentsse=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']")
        for r in discount_percentsse:
             discount_percentss.append(r.text)  
    except  NoSuchElementException as e: 
             discount_percentss.append(r.text)  
    time.sleep(1)

In [63]:
Brandss

['Kreverse',
 'D-SNEAKERZ',
 'SPARX',
 'woati',
 'Zsyto',
 'Chevit',
 'SHOEFLY',
 'Echor',
 'SHOEFLY',
 'Axter',
 'bluemaker',
 'HRX by Hrithik Roshan',
 'India hub',
 'BIRDE',
 'SPARX',
 'Numenzo',
 'SPARX',
 'SPARX',
 'Chevit',
 'Nilatin',
 'RODDICK SHOES',
 'India hub',
 'BRUTON',
 'Echor',
 'T-ROCK',
 'SPARX',
 'RODDICK SHOES',
 'RED TAPE',
 'Kraasa',
 'Robbie jones',
 'BIRDE',
 'Bonexy',
 'SHOEFLY',
 'Zorth',
 'PUMA',
 'Zorth',
 'PUMA',
 'World Wear Footwear',
 'Robbie jones',
 'ROCKFIELD',
 'Red Rose',
 'Baogi',
 'Magnolia',
 'Chevit',
 'BRUTON',
 'Chevit',
 'ASTEROID',
 'U.S. POLO ASSN.',
 'Longwalk',
 'luxury fashion',
 'PEHANOSA',
 'sixXplus',
 'Creer',
 'ASTEROID',
 'Numenzo',
 'SHILISHA',
 'BIRDE',
 'Numenzo',
 'SCATCHITE',
 'ROCKFIELD',
 'Shoes Bank',
 'Absolute comfort',
 'Numenzo',
 'SHILISHA',
 'Arohi',
 'VIPSJAZZY',
 'RODDICK SHOES',
 'ROCKFIELD',
 'Airland',
 'believe',
 'World Wear Footwear',
 'Magnolia',
 'Robbie jones',
 'restinfoot',
 'bluemaker',
 'Absolutee shoes',
 'Numenzo',
 'Kraasa',
 'HOC',
 'Extoes']

In [64]:
Product_descs

['Sneakers For Men',
 "Casual , Partywear Sneakers Shoes For Men's And Boys Wh...",
 'Smart Casuals Canvas Shoes Combo pack of 2 Sneakers For...',
 'Combo Men Pack of 2 Loafers Shoes Sneakers For Men',
 "Men's Sneakers Walking Shoes - Lightweight Classic Whit...",
 'Combo Men Pack of 2 Loafers Shoes Sneakers For Men',
 'New Collection of Combo Pack of 2 Stylish Shoes Sneaker...',
 'casual for men (beige 06) Sneakers For Men',
 'Sneakers For Men',
 'Combo Pack of 2 Casual Shoes Sneakers For Men',
 'SM-322 Sneakers For Men',
 'Sneakers For Men',
 'Men White Sneakers Sneakers For Men',
 'SM-675 Sneakers For Men',
 'Unique & Perfect Collection Combo Pack of 02 Shoes for ...',
 'Black Sneaker For Men Sneakers For Men',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'Fashionable sneaker casual shoes Sneakers For Men',
 'Mens Walking Running Shoes - Lightweight Breathable Mes...',
 'Synthetic Leather Casual Partywear Wedding Sneakers Sho...',
 'SM-162 Sneakers For Men',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'Shark-41 Sneakers For Men',
 'Casual Sneakers Shoes For Men Sneakers For Men',
 'Birde Trendy Casual Shoes Sneakers For Men',
 'Sneakers For Men',
 'Combo Men Pack of 2 Loafers Shoes Sneakers For Men',
 'Sneakers For Men',
 'Puma Smash Vulc Sneakers For Men',
 'Sneakers For Men',
 'Kor Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Super Stylish & Trendy Combo Pack of 02 Pairs Sneakers ...',
 'Combo Pack Of 4 Casual Shoes Loafer Shoes Sneakers For ...',
 'Perfect & Affordable Combo Pack of 02 Pairs Sneakers Ou...',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'LEBRON 2.0 Sneakers For Men',
 'Men Boxer Sneakers For Men',
 'Luxury Fashionable casual sneaker shoes Sneakers For Me...',
 'Sneakers For Men',
 'Casual Sneakers black Shoes For Men Sneakers For Men',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Unique & Perfect Collection Shoes for Men Casual Sneake...',
 'Birde Trendy Casual Shoes Sneakers For Men',
 'Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Sneakers For Men',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Sneakers For Men',
 'Casual Sneakers Shoes For Men Sneakers For Men Sneakers...',
 'Sneakers For Men',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'Sneakers For Men',
 'shoe Sneakers For Men',
 'Sneakers for men(black_6) Sneakers For Men',
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'White Sneakers Sneakers For Men',
 'Sneakers For Men',
 "Casual shoes,Sneakers for men's,shoes for men's Sneaker...",
 'casual for men (blue 10) Sneakers For Men',
 'ABSOLUTEE SHOES ORANGE GYM SHOE FOR MEN Sneakers For Me...',
 'Sneakers For Men',
 'Series 7 Sneakers For Men',
 'Luxury Fashionable Breathable Casual Sneakers Shoes For...',
 'Relaxed Attractive Combo pack of 3 Sneakers For Men']

In [65]:
pricess

['₹266',
 '₹348',
 '₹649',
 '₹499',
 '₹398',
 '₹322',
 '₹362',
 '₹399',
 '₹362',
 '₹599',
 '₹404',
 '₹1,699',
 '₹449',
 '₹472',
 '₹769',
 '₹449',
 '₹623',
 '₹735',
 '₹420',
 '₹449',
 '₹474',
 '₹399',
 '₹168',
 '₹399',
 '₹379',
 '₹730',
 '₹474',
 '₹899',
 '₹444',
 '₹399',
 '₹283',
 '₹379',
 '₹362',
 '₹435',
 '₹1,900',
 '₹434',
 '₹1,400',
 '₹240',
 '₹499',
 '₹499',
 '₹379',
 '₹378',
 '₹356',
 '₹536',
 '₹474',
 '₹447',
 '₹499',
 '₹2,399',
 '₹236',
 '₹379',
 '₹378',
 '₹499',
 '₹398',
 '₹499',
 '₹449',
 '₹449',
 '₹359',
 '₹449',
 '₹398',
 '₹499',
 '₹349',
 '₹198',
 '₹429',
 '₹399',
 '₹460',
 '₹399',
 '₹474',
 '₹449',
 '₹250',
 '₹449',
 '₹240',
 '₹311',
 '₹499',
 '₹349',
 '₹404',
 '₹629',
 '₹398',
 '₹444',
 '₹378',
 '₹597']

In [66]:
discount_percentss

['73% off',
 '47% off',
 '7% off',
 '50% off',
 '69% off',
 '67% off',
 '72% off',
 '60% off',
 '63% off',
 '39% off',
 '59% off',
 '56% off',
 '85% off',
 '52% off',
 '23% off',
 '77% off',
 '16% off',
 '8% off',
 '71% off',
 '65% off',
 '52% off',
 '80% off',
 '71% off',
 '60% off',
 '62% off',
 '23% off',
 '52% off',
 '78% off',
 '55% off',
 '60% off',
 '43% off',
 '62% off',
 '63% off',
 '56% off',
 '49% off',
 '56% off',
 '64% off',
 '51% off',
 '50% off',
 '50% off',
 '24% off',
 '62% off',
 '64% off',
 '66% off',
 '86% off',
 '75% off',
 '75% off',
 '40% off',
 '52% off',
 '70% off',
 '62% off',
 '50% off',
 '60% off',
 '50% off',
 '65% off',
 '55% off',
 '28% off',
 '77% off',
 '60% off',
 '50% off',
 '65% off',
 '60% off',
 '66% off',
 '60% off',
 '53% off',
 '60% off',
 '52% off',
 '55% off',
 '49% off',
 '55% off',
 '51% off',
 '68% off',
 '50% off',
 '65% off',
 '59% off',
 '68% off',
 '60% off',
 '55% off',
 '81% off',
 '60% off']

In [67]:
#joining the two list we got from page 1 to 4
Brands.extend(Brandss)
Product_desc.extend(Product_descs)
prices.extend(pricess)
discount_percents.extend(discount_percentss)

In [68]:
Brands

['woati',
 'Echor',
 'Chevit',
 'Magnolia',
 'BRUTON',
 'Chevit',
 'ASTEROID',
 'HRX by Hrithik Roshan',
 'Longwalk',
 'luxury fashion',
 'PEHANOSA',
 'Numenzo',
 'Creer',
 'ASTEROID',
 'Numenzo',
 'Bonexy',
 'BIRDE',
 'Numenzo',
 'SCATCHITE',
 'Echor',
 'Shoes Bank',
 'Absolute comfort',
 'Numenzo',
 'RED TAPE',
 'Arohi',
 'VIPSJAZZY',
 'RODDICK SHOES',
 'Bonexy',
 'Airland',
 'believe',
 'World Wear Footwear',
 'Zorth',
 'Robbie jones',
 'restinfoot',
 'bluemaker',
 'Chevit',
 'Numenzo',
 'Kraasa',
 'HOC',
 'ROCKFIELD',
 'Kreverse',
 'D-SNEAKERZ',
 'SPARX',
 'woati',
 'Zsyto',
 'Chevit',
 'SHOEFLY',
 'Echor',
 'SHOEFLY',
 'Axter',
 'bluemaker',
 'HRX by Hrithik Roshan',
 'India hub',
 'BIRDE',
 'SPARX',
 'Numenzo',
 'SPARX',
 'SPARX',
 'Chevit',
 'Nilatin',
 'RODDICK SHOES',
 'India hub',
 'BRUTON',
 'Echor',
 'T-ROCK',
 'SPARX',
 'RODDICK SHOES',
 'RED TAPE',
 'Kraasa',
 'Robbie jones',
 'BIRDE',
 'Bonexy',
 'SHOEFLY',
 'Zorth',
 'PUMA',
 'Zorth',
 'PUMA',
 'World Wear Footwear',
 'Robbie jones',
 'ROCKFIELD',
 'Red Rose',
 'Baogi',
 'Magnolia',
 'Chevit',
 'BRUTON',
 'Chevit',
 'ASTEROID',
 'U.S. POLO ASSN.',
 'Longwalk',
 'luxury fashion',
 'PEHANOSA',
 'sixXplus',
 'Creer',
 'ASTEROID',
 'Numenzo',
 'SHILISHA',
 'BIRDE',
 'Numenzo',
 'SCATCHITE',
 'ROCKFIELD',
 'Shoes Bank',
 'Absolute comfort',
 'Numenzo',
 'SHILISHA',
 'Arohi',
 'VIPSJAZZY',
 'RODDICK SHOES',
 'ROCKFIELD',
 'Airland',
 'believe',
 'World Wear Footwear',
 'Magnolia',
 'Robbie jones',
 'restinfoot',
 'bluemaker',
 'Absolutee shoes',
 'Numenzo',
 'Kraasa',
 'HOC',
 'Extoes']

In [69]:
len(Brands)

120

In [70]:
Product_desc

["Men's Sneakers Walking Shoes - Lightweight Classic Whit...",
 'Super Stylish & Trendy Combo Pack of 02 Pairs Sneakers ...',
 'Sneakers For Men',
 'Combo Pack Of 4 Casual Shoes Loafer Shoes Sneakers For ...',
 'Perfect & Affordable Combo Pack of 02 Pairs Sneakers Ou...',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Sneakers For Men',
 'Men Boxer Sneakers For Men',
 'Luxury Fashionable casual sneaker shoes Sneakers For Me...',
 'Sneakers For Men',
 'Sneakers For Men',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Birde Trendy Casual Shoes Sneakers For Men',
 'Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Mens Walking Running Shoes - Lightweight Breathable Mes...',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Sneakers For Men',
 'Sneakers For Men',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'Sneakers For Men',
 'shoe Sneakers For Men',
 'Sneakers for men(black_6) Sneakers For Men',
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'Sneakers For Men',
 'Sneakers For Men',
 "Casual shoes,Sneakers for men's,shoes for men's Sneaker...",
 'casual for men (blue 10) Sneakers For Men',
 'Combo Pack of 4 Casual Sneakers With Sneakers For Men',
 'Sneakers For Men',
 'Series 7 Sneakers For Men',
 'Luxury Fashionable Breathable Casual Sneakers Shoes For...',
 'Sneakers For Men',
 'Sneakers For Men',
 "Casual , Partywear Sneakers Shoes For Men's And Boys Wh...",
 'Smart Casuals Canvas Shoes Combo pack of 2 Sneakers For...',
 'Combo Men Pack of 2 Loafers Shoes Sneakers For Men',
 "Men's Sneakers Walking Shoes - Lightweight Classic Whit...",
 'Combo Men Pack of 2 Loafers Shoes Sneakers For Men',
 'New Collection of Combo Pack of 2 Stylish Shoes Sneaker...',
 'casual for men (beige 06) Sneakers For Men',
 'Sneakers For Men',
 'Combo Pack of 2 Casual Shoes Sneakers For Men',
 'SM-322 Sneakers For Men',
 'Sneakers For Men',
 'Men White Sneakers Sneakers For Men',
 'SM-675 Sneakers For Men',
 'Unique & Perfect Collection Combo Pack of 02 Shoes for ...',
 'Black Sneaker For Men Sneakers For Men',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'Fashionable sneaker casual shoes Sneakers For Men',
 'Mens Walking Running Shoes - Lightweight Breathable Mes...',
 'Synthetic Leather Casual Partywear Wedding Sneakers Sho...',
 'SM-162 Sneakers For Men',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'Shark-41 Sneakers For Men',
 'Casual Sneakers Shoes For Men Sneakers For Men',
 'Birde Trendy Casual Shoes Sneakers For Men',
 'Sneakers For Men',
 'Combo Men Pack of 2 Loafers Shoes Sneakers For Men',
 'Sneakers For Men',
 'Puma Smash Vulc Sneakers For Men',
 'Sneakers For Men',
 'Kor Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Super Stylish & Trendy Combo Pack of 02 Pairs Sneakers ...',
 'Combo Pack Of 4 Casual Shoes Loafer Shoes Sneakers For ...',
 'Perfect & Affordable Combo Pack of 02 Pairs Sneakers Ou...',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'LEBRON 2.0 Sneakers For Men',
 'Men Boxer Sneakers For Men',
 'Luxury Fashionable casual sneaker shoes Sneakers For Me...',
 'Sneakers For Men',
 'Casual Sneakers black Shoes For Men Sneakers For Men',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Unique & Perfect Collection Shoes for Men Casual Sneake...',
 'Birde Trendy Casual Shoes Sneakers For Men',
 'Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Sneakers For Men',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Sneakers For Men',
 'Casual Sneakers Shoes For Men Sneakers For Men Sneakers...',
 'Sneakers For Men',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'Sneakers For Men',
 'shoe Sneakers For Men',
 'Sneakers for men(black_6) Sneakers For Men',
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'White Sneakers Sneakers For Men',
 'Sneakers For Men',
 "Casual shoes,Sneakers for men's,shoes for men's Sneaker...",
 'casual for men (blue 10) Sneakers For Men',
 'ABSOLUTEE SHOES ORANGE GYM SHOE FOR MEN Sneakers For Me...',
 'Sneakers For Men',
 'Series 7 Sneakers For Men',
 'Luxury Fashionable Breathable Casual Sneakers Shoes For...',
 'Relaxed Attractive Combo pack of 3 Sneakers For Men']

In [71]:
len(Product_desc)

102

In [72]:
prices

['₹499',
 '₹399',
 '₹536',
 '₹356',
 '₹474',
 '₹447',
 '₹499',
 '₹1,699',
 '₹236',
 '₹379',
 '₹378',
 '₹449',
 '₹398',
 '₹499',
 '₹449',
 '₹474',
 '₹359',
 '₹449',
 '₹398',
 '₹399',
 '₹349',
 '₹198',
 '₹429',
 '₹899',
 '₹460',
 '₹399',
 '₹474',
 '₹379',
 '₹250',
 '₹449',
 '₹240',
 '₹434',
 '₹499',
 '₹349',
 '₹404',
 '₹424',
 '₹398',
 '₹444',
 '₹378',
 '₹499',
 '₹266',
 '₹348',
 '₹649',
 '₹499',
 '₹398',
 '₹322',
 '₹362',
 '₹399',
 '₹362',
 '₹599',
 '₹404',
 '₹1,699',
 '₹449',
 '₹472',
 '₹769',
 '₹449',
 '₹623',
 '₹735',
 '₹420',
 '₹449',
 '₹474',
 '₹399',
 '₹168',
 '₹399',
 '₹379',
 '₹730',
 '₹474',
 '₹899',
 '₹444',
 '₹399',
 '₹283',
 '₹379',
 '₹362',
 '₹435',
 '₹1,900',
 '₹434',
 '₹1,400',
 '₹240',
 '₹499',
 '₹499',
 '₹379',
 '₹378',
 '₹356',
 '₹536',
 '₹474',
 '₹447',
 '₹499',
 '₹2,399',
 '₹236',
 '₹379',
 '₹378',
 '₹499',
 '₹398',
 '₹499',
 '₹449',
 '₹449',
 '₹359',
 '₹449',
 '₹398',
 '₹499',
 '₹349',
 '₹198',
 '₹429',
 '₹399',
 '₹460',
 '₹399',
 '₹474',
 '₹449',
 '₹250',
 '₹449',
 '₹240',
 '₹311',
 '₹499',
 '₹349',
 '₹404',
 '₹629',
 '₹398',
 '₹444',
 '₹378',
 '₹597']

In [73]:
len(prices)

120

In [74]:
discount_percents

['50% off',
 '60% off',
 '66% off',
 '64% off',
 '86% off',
 '75% off',
 '75% off',
 '56% off',
 '52% off',
 '70% off',
 '62% off',
 '77% off',
 '60% off',
 '50% off',
 '65% off',
 '52% off',
 '28% off',
 '77% off',
 '60% off',
 '60% off',
 '65% off',
 '60% off',
 '66% off',
 '78% off',
 '53% off',
 '60% off',
 '52% off',
 '62% off',
 '49% off',
 '55% off',
 '51% off',
 '56% off',
 '50% off',
 '65% off',
 '59% off',
 '78% off',
 '60% off',
 '55% off',
 '81% off',
 '50% off',
 '73% off',
 '47% off',
 '7% off',
 '50% off',
 '69% off',
 '67% off',
 '72% off',
 '60% off',
 '63% off',
 '39% off',
 '59% off',
 '56% off',
 '85% off',
 '52% off',
 '23% off',
 '77% off',
 '16% off',
 '8% off',
 '71% off',
 '65% off',
 '52% off',
 '80% off',
 '71% off',
 '60% off',
 '62% off',
 '23% off',
 '52% off',
 '78% off',
 '55% off',
 '60% off',
 '43% off',
 '62% off',
 '63% off',
 '56% off',
 '49% off',
 '56% off',
 '64% off',
 '51% off',
 '50% off',
 '50% off',
 '24% off',
 '62% off',
 '64% off',
 '66% off',
 '86% off',
 '75% off',
 '75% off',
 '40% off',
 '52% off',
 '70% off',
 '62% off',
 '50% off',
 '60% off',
 '50% off',
 '65% off',
 '55% off',
 '28% off',
 '77% off',
 '60% off',
 '50% off',
 '65% off',
 '60% off',
 '66% off',
 '60% off',
 '53% off',
 '60% off',
 '52% off',
 '55% off',
 '49% off',
 '55% off',
 '51% off',
 '68% off',
 '50% off',
 '65% off',
 '59% off',
 '68% off',
 '60% off',
 '55% off',
 '81% off',
 '60% off']

In [77]:
len(discount_percents)

120

In [79]:
Nos=[]
for i in range(1,len(Brands)+1):
    Nos.append(i)
Nos

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120]

In [80]:
import pandas as pd
SNeaker_SHoe=pd.DataFrame({})
SNeaker_SHoe['Nos']=Nos[:100]
SNeaker_SHoe['SNEAKER SHOE BRAND NAME']=Brands[:100]
SNeaker_SHoe['Product Description']=Product_desc[:100]
SNeaker_SHoe['Price']=prices[:100]
SNeaker_SHoe['Discount Percentage']=discount_percents[:100]
SNeaker_SHoe.style.hide_index()

These are the first 100 sneakers from  FlipKart